"""add_pipeline_tracking_columns

Revision ID: 3e41fc2d358f
Revises: e0a9e73a4948
Create Date: 2026-04-02 23:39:08.305605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e41fc2d358f'
down_revision: Union[str, None] = 'e0a9e73a4948'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('presentations', sa.Column('input_modified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('presentations', sa.Column('plan_modified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('presentations', sa.Column('content_modified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('presentations', sa.Column('design_modified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('presentations', sa.Column('last_exported_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('presentations', 'last_exported_at')
    op.drop_column('presentations', 'design_modified_at')
    op.drop_column('presentations', 'content_modified_at')
    op.drop_column('presentations', 'plan_modified_at')
    op.drop_column('presentations', 'input_modified_at')
    # ### end Alembic commands ###
