"""add_objects_json_to_variations

Revision ID: 6d4f40c1e044
Revises: 94373b7aba3a
Create Date: 2026-04-04 14:46:08.245754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d4f40c1e044'
down_revision: Union[str, None] = '94373b7aba3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('template_variations', sa.Column('objects_json', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('template_variations', 'objects_json')
    # ### end Alembic commands ###
