"""create_presentations_table

Revision ID: 7d359c6fddf3
Revises: a5c7911eebd2
Create Date: 2026-04-02 19:34:47.097261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d359c6fddf3'
down_revision: Union[str, None] = 'a5c7911eebd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('presentations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('draft', 'input_complete', 'plan_complete', 'content_complete', 'design_complete', 'exported', name='presentationstatus'), nullable=False),
    sa.Column('language', sa.Enum('english', 'arabic', 'bilingual', name='presentationlanguage'), nullable=False),
    sa.Column('tone', sa.String(length=100), nullable=True),
    sa.Column('audience', sa.String(length=100), nullable=True),
    sa.Column('slide_count', sa.Integer(), nullable=False),
    sa.Column('llm_provider', sa.String(length=50), nullable=True),
    sa.Column('llm_model', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('presentations')
    # ### end Alembic commands ###
